source 'https://rubygems.org'
gem 'jekyll', '>= 3.8.4'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-gist'
gem 'jekyll-octopod'
gem 'rack', '>= 1.6.12'
gem 'jekyll-paginate'
gem 'jemoji'
gem 'jekyll-include-cache'